[package]
name = "continuous-testing"
version = "0.2.3"
edition = "2021"
description = "A continuous testing tool"
license = "GPL-2.0-or-later"
repository = "https://github.com/taishingi/continuous-testing"


[[bin]]
name = "again"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eywa = "0.2.0"
