#!/bin/bash

unset GIT_DIR

DWL_URL="https://github.com/taishingi/continuous-template/archive/refs/tags/0.0.5.zip"
RELEASE="0.0.5.zip"
SUM="b54e5a4a153fe9aac4bc2482c53260c5d7f23b6e551156a67588563be737c513  ${RELEASE}"
DIR=$(realpath .)
BRANCHES=('master')
REMOTES=('origin')
PROVIDER=
USERNAME=
REPOSITORY=

function ask()
{
    
    while [ -z ${PROVIDER} ]
    then
        echo "Enter tour provider [github.com|gitlab.com]"
        read -p $PROVIDER
    fi
    
    while [ -z ${USERNAME} ]
    do
        echo "Enter your ${provider} username"
        read -p $USERNAME
    done
    
    while [ -z ${REPOSITORY} ]
    do
        echo "Enter your ${provider} repository name"
        read -p $REPOSITORY
    done
    
    if [ "HTTP/2 200" != $(curl -Is "https://${PROVIDER}/${USERNAME}/${REPOSITORY}" | head -n 1) ]
    then
        PROVIDER=""
        USERNAME=""
        REPOSITORY=""
        ask
    else
        if [ -f "dub.json" ]
        then
            cd continuous/d || exit 1
            ./scripts-gen "${PROVIDER}" "${USERNAME}" "${REPOSITORY}" || exit 1
        elif [ -f "Cargo.toml" ]
        then
            cd continuous/rust || exit 1
            ./scripts-gen "${PROVIDER}" "${USERNAME}" "${REPOSITORY}" || exit 1
        else
            cd continuous/go || exit 1
            ./scripts-gen "${PROVIDER}" "${USERNAME}" "${REPOSITORY}" || exit 1
        fi
    fi
}
function download() {
    
    if [ -f "$DIR/${RELEASE}" ]
    then
        rm "${DIR}/${RELEASE}"
    fi
    
    wget --quiet "${DWL_URL}" || exit 1
    
    DOWN_SUM=$(sha256sum ${RELEASE})
    echo $DOWN_SUM
    if [ "${SUM}" == "${DOWN_SUM}" ]
    then
        echo "Signature OK"
        if [ -d "./continuous" ]
        then
            rm -rf ./continuous
        fi
        unzip ${RELEASE} || exit 1
        mv "continuous-template-0.0.5" continuous || exit 1
        ask
        exit 0
    else
        echo "Bad sum"
        exit 1
    fi
}

function main() {
    if [ -d "continuous" ]
    then
        if [ -f "Cargo.toml" ]
        then
            cd continuous/rust || exit 1
            packer validate . || exit 1
            packer build . || exit 1
            exit 0
        elif [ -f "dub.json" ]
        then
            cd continuous/d || exit 1
            packer validate . || exit 1
            packer build . || exit 1
            exit 0
        else
            cd continuous/go || exit 1
            packer validate . || exit 1
            packer build . || exit 1
            exit 0
        fi
    else
        download || exit 1
        rm "${DIR}/${RELEASE}" || exit 1
        exit 0
    fi
}

function send()
{
    if [ -d "${DIR}/continuous" ];then
        
        for r in "${REMOTES[@]}";do
            for b in "${BRANCHES[@]}";do
                git push "${r}" "${b}"
                git push "${r}" --tags
            done
        done
    fi
}

send

main
