name: zuu
on:
  push:
    branches: [ "master" , "develop" ]
  pull_request:
    branches: [ "master" , "develop"  ]
env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color
  USER: taishingi
jobs:
  zuu:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: sudo apt-get install -y git wget && git clone https://github.com/taishingi/continuous-testing.git c && cd c && cargo install --path .
    - name: zuu
      run:  wget https://raw.githubusercontent.com/taishingi/zuu/master/pre-commit && bash pre-commit
    
